#!/bin/bash

set -xe

if [[ -f ~/.background ]]; then
	background=`cat ~/.background`
else
	background=light
fi

if [[ "$background" == "light" ]]; then
	background=dark
	cp ~/.alacritty.yml.dark ~/.alacritty.yml
	sed -i '' 's/set background=.*/set background=dark/' ~/.vimrc
else
	background=light
	cp ~/.alacritty.yml.light ~/.alacritty.yml
	sed -i '' 's/set background=.*/set background=light/' ~/.vimrc
fi

echo $background > ~/.background
